genome/ptero-workflow

ptero_workflow/api/v1/reports/__init__.py
ptero_workflow/api/v1/views.py
setup.cfg

Fixes #75 
This PR addresses the immediate problem entry_points not being supported by our Deis deployment, but it leaves the reports largely untested.  Testing of the reports endpoints will be addressed in #6.

move reports register from setup.cfg to reports/__init__.py

---

ptero_workflow/implementation/celery_app.py
ptero_workflow/implementation/factory.py
tests/scripts/Procfile

Solve some concurrency issues with connecting to Postgresql which were exposed when deploying to deis.

Worker process init

---

requirements.txt
scripts/purge-backends

As with genome/ptero-petri#69, this adds `ptero-common` as a requirement, and adds `scripts/purge-backends`.

Add purge backends script

---

ptero_workflow/api/wsgi.py
tests/scripts/Procfile

wgsi.py picks up the port assignment from the environment instead of a command line option

Ptero workflow host and port

---

.travis.yml
ptero_workflow/implementation/models/json_type.py
ptero_workflow/implementation/models/task/task_base.py
run_system_test
tests/api/v1/generator/base_case.py
tests/api/v1/system_tests/nested_parallel_by_operation_matrix_fail/result.json
tests/api/v1/system_tests/nested_parallel_by_operation_matrix_fail/submit.json
tests/api/v1/system_tests/nested_parallel_by_operation_matrix_fail/workflow_details.json
tests/api/v1/system_tests/parallel_by_scalar_input/result.json
tests/api/v1/system_tests/parallel_by_scalar_input/submit.json
tests/api/v1/system_tests/parallel_by_scalar_input/workflow_details.json
tox.ini

Handle parallel task with scalar input

---

ptero_workflow/implementation/backend.py
ptero_workflow/implementation/celery_app.py
ptero_workflow/implementation/celery_tasks/submit_net.py
ptero_workflow/implementation/factory.py

Closes #124 
This PR is not using a handler or the task_postrun signal to close the database session.

Celery app refactor

---

ptero_workflow/api/v1/schemas/post_workflow.json
ptero_workflow/implementation/models/methods/__init__.py
ptero_workflow/implementation/models/methods/block.py
ptero_workflow/implementation/models/methods/converge.py
tests/api/v1/system_tests/converge/result.json
tests/api/v1/system_tests/converge/submit.json
tests/api/v1/system_tests/n_shaped_with_block/result.json
tests/api/v1/system_tests/n_shaped_with_block/submit.json
tests/api/v1/test_roundtrip_success.py
tox.ini

There is probably some room for deduplication by making a base-class for instance.  I didn't do this since the Block Method may be short-lived, and removing it would remove the duplication.

Block n converge

---

ptero_workflow/api/v1/schemas/post_workflow.json
ptero_workflow/implementation/backend.py
ptero_workflow/implementation/models/workflow.py
tests/api/v1/system_tests/nested_parallel_by_operation_minimal/result.json
tests/api/v1/system_tests/nested_parallel_by_operation_minimal/submit.json
tests/api/v1/test_post_duplicate_workflow_failure.py
tests/api/v1/test_roundtrip_success.py
tox.ini

Workflow names

---

ptero_workflow/implementation/backend.py
tests/api/v1/test_post_workflow_failure.py

better error message when inputs are missing

---

ptero_workflow/api/v1/views.py
ptero_workflow/implementation/backend.py
tests/api/base.py
tests/api/v1/test_query_workflow.py

Query workflow name

---

ptero_workflow/api/v1/views.py
ptero_workflow/implementation/backend.py
tests/api/v1/test_query_workflow.py

Include report when querying by workflow name

---

ptero_workflow/api/v1/views.py
ptero_workflow/implementation/backend.py
ptero_workflow/implementation/factory.py
ptero_workflow/implementation/models/execution/execution_base.py
ptero_workflow/implementation/models/input_source.py
ptero_workflow/implementation/models/link.py
ptero_workflow/implementation/models/methods/block.py
ptero_workflow/implementation/models/methods/converge.py
ptero_workflow/implementation/models/methods/dag.py
ptero_workflow/implementation/models/methods/method_base.py
ptero_workflow/implementation/models/result.py
ptero_workflow/implementation/models/task/input_connector.py
ptero_workflow/implementation/models/task/method_list.py
ptero_workflow/implementation/models/task/task_base.py
ptero_workflow/implementation/models/webhook.py
ptero_workflow/implementation/models/workflow.py
ptero_workflow/implementation/tasks.py

This is already deployed to our deis cluster.  The Genome::Process tests have just passed for the first time.  A query to the workflow-details endpoint for the trio workflow only takes 12.8 seconds (down from 120 seconds).

Performance and details

---

.travis.yml
tox.ini

Always test with postgresql

---

ptero_workflow/api/application.py

without zlib.MAX_WBITS|16 you get an error:
zlib.error: Error -3 while decompressing data: incorrect header check
Solution found here:
http://stackoverflow.com/questions/1838699/how-can-i-decompress-a-gzip-stream-with-zlib

Fix zlib decompression

---

ptero_workflow/api/v1/views.py
tests/api/v1/test_post_workflow_failure.py

Json schema stuff

---

tests/scripts/Procfile-for-lsf
tox.ini

A work inprogress.
We probably should merge genome/ptero-lsf/pull/36 before this would work.

Make it possible to test lsf integration

---

ptero_workflow/implementation/exceptions.py
ptero_workflow/implementation/models/methods/job.py

Since TravisCI will only run the shell-command system tests,I've run the lsf test locally and it passes.  We will be adding a Jenkins job to test the lsf system tests soon, once an appropriately provisioned vm is available.
Closes #185

Validate jobId from job service webhooks

---

.travis.yml
scripts/purge-backends
tox.ini

Require genome/ptero-common#37 to be merged first.

Conform to new janitor api

---

ptero_workflow/implementation/models/methods/block.py
ptero_workflow/implementation/models/methods/converge.py
ptero_workflow/implementation/models/methods/dag.py
ptero_workflow/implementation/models/methods/job.py
ptero_workflow/implementation/models/methods/method_base.py
ptero_workflow/implementation/models/task/input_connector.py
ptero_workflow/implementation/models/task/task_base.py

Just in time executions

---

.travis.yml
ptero_workflow/implementation/backend.py
requirements.txt

Add gitSha to server-info endpoint

---

ptero_workflow/implementation/models/methods/job.py
ptero_workflow/implementation/models/task/input_connector.py
ptero_workflow/implementation/models/task/task_base.py

KeyError 'jobId' should never happen again.
DAG executions are now updated to 'running'

Various Bug Fixes

---

ptero_workflow/api/v1/schemas/post_workflow.json
ptero_workflow/implementation/backend.py
ptero_workflow/implementation/models/execution/method_execution.py
ptero_workflow/implementation/models/methods/dag.py
ptero_workflow/implementation/models/methods/job.py
ptero_workflow/implementation/models/methods/method_base.py
ptero_workflow/implementation/tasks.py
tests/api/v1/test_cancel_workflow.py
tests/api/v1/test_roundtrip_success.py
tests/api/v1/test_webhooks.py

Closes #43
In order to test this I made it possible to specify webhooks to be sent by the job service.

Hard cancel

---

ptero_workflow/api/application.py
ptero_workflow/api/v1/api.py
ptero_workflow/api/v1/reports/workflow_executions.py
ptero_workflow/api/v1/views.py
ptero_workflow/implementation/models/execution/execution_base.py
ptero_workflow/implementation/models/methods/method_base.py
ptero_workflow/implementation/models/workflow.py
requirements.txt
test-requirements.txt

Bump dependencies

---

ptero_workflow/implementation/backend.py
tests/api/base.py
tests/api/v1/test_callback_handlers.py

Callback handler 404

---

ptero_workflow/api/v1/api.py
ptero_workflow/api/v1/reports/workflow_executions.py
ptero_workflow/api/v1/views.py
ptero_workflow/implementation/backend.py
ptero_workflow/implementation/celery_app.py
ptero_workflow/implementation/celery_tasks/__init__.py
ptero_workflow/implementation/celery_tasks/submit_job.py
ptero_workflow/implementation/models/execution/execution_base.py
ptero_workflow/implementation/models/methods/job.py
ptero_workflow/implementation/models/methods/method_base.py
ptero_workflow/implementation/models/task/task_base.py
ptero_workflow/implementation/models/webhook.py
ptero_workflow/implementation/models/workflow.py
ptero_workflow/urls.py
tests/api/v1/test_webhooks.py

Breaking chains

---

ptero_workflow/alembic/versions/2b63dddbaa74_set_backfilled_execution_columns_non_.py
ptero_workflow/alembic/versions/5005862095e3_backfill_execution_status_history_.py
ptero_workflow/alembic/versions/539a0ab6e387_status_history_workflow_id.py
ptero_workflow/alembic/versions/d7a33203c5f5_timestamp_executions.py
ptero_workflow/alembic/versions/e45908a7e045_backfill_execution_timestamps.py
ptero_workflow/api/v1/reports/__init__.py
ptero_workflow/api/v1/reports/limited_workflow_executions.py
ptero_workflow/api/v1/reports/limited_workflow_status_updates.py
ptero_workflow/api/v1/reports/spawned_workflows.py
ptero_workflow/implementation/backend.py
ptero_workflow/implementation/models/execution/execution_base.py
ptero_workflow/implementation/models/execution/method_execution.py

Limited (paged) reports

---

ptero_workflow/implementation/backend.py
tests/api/v1/test_bad_job_parameters_specified.py

Bugfix: bad job parameters cause 'errored' status

---

ptero_workflow/alembic/versions/89b1fb28bb6c_store_service_data.py
ptero_workflow/api/v1/schemas/post_workflow.json
ptero_workflow/implementation/model_builder.py
ptero_workflow/implementation/models/execution/execution_base.py
ptero_workflow/implementation/models/methods/job.py
tests/api/v1/test_saving_service_data.py

This can be configured by specifying `serviceDataToSave` on a Job Method.

Store service data on executions
